version: 1
formatters:
  brief:
    format: "%(asctime)s - %(message)s"
  simple:
    format: "%(asctime)s %(levelname)-8s: %(message)s"
handlers:
  file:
    class : logging.FileHandler
    formatter: simple
    level: DEBUG
    filename: BecomeHuman.log
    encoding: utf-8
loggers:
  general:
    level: DEBUG
    handlers: [file]